language: rust
jobs:
  include:
    - stage: build
      script:
        - rustup target add x86_64-unknown-linux-musl
        - cargo build --target x86_64-unknown-linux-musl --release
        - strip target/x86_64-unknown-linux-musl/release/buttons
        - mkdir target/work
        - cp -t target/work LICENSE README.md target/x86_64-unknown-linux-musl/release/buttons
        - tar -czvf buttons-"${TRAVIS_TAG:-untagged}".tar.gz -C target/work .
      deploy:
        provider: releases
        token: $GITHUB_OAUTH_TOKEN
        file: buttons-*.tar.gz
        edge: true
        on:
          tags: true
